### ISSUE TITLE
dbptk - desktop - can't save database information metadata

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-developer#474]
Gives error:
![image](https://user-images.githubusercontent.com/3479156/104189763-cb84d200-5423-11eb-8809-b0dab68dda66.png)

**Comment by hmiguim** [comment]
Please provide the version of DBPTK Desktop you are using and which action were you doing?

**Comment by Laurira** [comment]
I am using DBPTK Desktop 2.5.3 on Ubuntu. I made a discovery that I can use DBPTK-Desktop as DBPTK-Enterprise for sharing out siard for archivists. When DBPTK-Desktop is running then actually I can use it via browser as well 192.168.XX.YY:38499/#database
It is very nice feature.

Now I made second discovery that I tried to edit SIARD file via browser and that were the place when this error occurred. If I try to edit SIARD directly then everything works as expected.

If this feature is something that you think may be useful for your other product users as well then maybe you should think about fixing that error message or disable editing at all via browser. Otherwise close this issue.

But nice to hear from you. I have written an e-mail for you regarding one question about DBPTK-Developer command line vs. import-config. If you can answer that then that would be also nice.

Regards,
Lauri

**Comment by hmiguim** [comment]
DBPTK Desktop is intended to be use within the electron application because certain functionalities are fully dependent of electron API. 

Even tough you access DBPTK Desktop via web browser it didn't automatically transform it into DBPTK Enterprise. This is a problem that we'll tackle in a future iteration to not allow those kind of action to be taken.
