### ISSUE TITLE
Support for SIARD 2.2

### ISSUE THREAD

**Issue by seso-kdrs** [keeps/dbptk-developer#581]
Are there plans to support SIARD 2.2?

Currently the lack of support for SIARD 2.2 causes issues when working with files made in other software (e. g. SIARD Suite, Full Convert).

**Comment by luis100** [comment]
Hello, SIARD 2.2 support is on the roadmap for this year, stay tuned!

**Comment by Chlara** [comment]
I have the same problem. 

- What are the plans at the moment? 
- When can we expect support for version 2.2 (especially reading and validating)?

**Comment by luis100** [comment]
There is a new version comming in soon, but unfortunately still without SIARD 2.2 support. 
Roadmap has changed due to requests from sponsors, and support for SIARD 2.2 was delayed on behalf of:

- Support for reading SIARD DK in all DBPTK tools

And DBPTK Desktop and Enterprise features:
- Support for database access rights (user access permissions) including support for expiration date for that access permission
- Search across databases content, including selecting a set of databases, sensitive to user access permissions
- Database opt-out option for the search across databases
- Several other improvements and bug fixes and security updates

SIARD 2.2 support is now scheduled to start development on January.

**Comment by luis100** [comment]
@seso-kdrs @Chlara we are about to release SIARD 2.2 support for import, export and validation, but we would like to have some external testing before releasing, are you available for testing a pre-release version?

**Comment by MartinR4838** [comment]
I can provide some support for you too.

**Comment by solfeggietto** [comment]
I will offer my support and do time for testing in particular in interoperability issues

For example that DBPTK Developer can accept and find valid a SIARD-extraction with 
Part 1: lobFolder in Database level metadata (if missing points to root inside SIARD-file)
Part 2: lobFolder in Column level metadata
Part 3: file attribute path in a LOB column in table[n].xml

Understanding that DBPTK itself must keep supporting existing ways that been implemented in existing and previous versions.

Ref:
https://github.com/keeps/dbptk-developer/issues/476

**Comment by luis100** [comment]
Sorry for the delay producing the release candidate, when doing the release we found out that some tests (roundtrip tests when we put SIARD into a DB and back to SIARD and compare the result) that are only executed in Github when doing a release were failing, and we are still trying to fix those. Will get back to you as soon as we fix them.

**Comment by luis100** [comment]
Hello, for the purpose of this RC testing, we were considering only producing dbptk-developer.

**Comment by Chlara** [comment]
I made a short validation test on a simple SIARD 2.2 file (similar to SIARD 2.1). I found 2 Issues in the dbptk-validation-reporter file:

- [ ] Line 5: SIARD Version: 2.1 
- [ ] A_M_5.1-1-1: [WARNING] - The version of SIARD should be 1.0, DK, 2.0 or 2.1. Found: 2.2 - siardArchive

I will made more test in October.
